namespace: btd6teams

port: &app_port 8080

deployment:
  name: btd6
  image: ghcr.io/torbencarstens/btd6-teams:__TAG__
  imagePullPolicy: Always
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: btd6
  ports:
    - *app_port
  requests:
    cpu: 10m
    memory: 10Mi
  limit:
    cpu: 100m
    memory: 20Mi

service:
  name: btd6
  port: 80
  targetPort: *app_port
  appSelector: btd6

ingress:
  hosts:
    - btd6.carstens.tech
  secret: tls-btd6
  issuer: letsencrypt-issuer
  name: btd6

configmap:
  name: btd6teams
  port: *app_port
