name: Build/Publish docker image

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint --strict

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/torbencarstens/btd6-teams:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/torbencarstens/btd6-teams:${GITHUB_SHA}

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@v4
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - name: install helm chart
        uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          subcommand: upgrade
          release_name: btd6
          ref: .
          namespace: btd6teams
          install: true
          atomic: true
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
